### ISSUE TITLE
Enhance the IMainMenu interface

### ISSUE THREAD

**Issue by dhuebner** [jupyter/jupyterlab#836] opened 2016-09-02 08:58 UTC
I'm working on a wizard plugin for jupyterlab. The target is to have project wizards under the:
File -> New... -> My Project, MyProject2

Unfortunately there is no way to extend the contributed menu entries. The current workaround is to downcast the IMainMenu to `(<MainMenu>mainMenu) `in order to call `menus` to find the "File" entry. It would be nice to have `menus: ISequence<Menu> ` function available (see MenuBar) or at least getMenu(id: string).
I also think that an `id` should be added to Menu as required field in order to identify a particular menu or item. For the FileBrowser e.g. the commands prefix `file-operations` could be used as ID for the main menu entry.

**Comment by ellisonbg** [comment] 2016-09-06 19:01
@dhuebner that was a deliberate design decision. We spend months (quite literally) trying to figure out a way for plugins to add things to each other's menus without the API becoming exponentially complex. The issue you run into is how to define the sectioning/ordering of menu items when any plugins can contribute content to any menu and you allow submenus. We did it, but it was so complex no one could reason about the API.

The approach we have taken is that plugins "own" top level menus. This allows plugins to do whatever they need in that context, but limits the ability of plugins to mess with each other's menus.

The "File" menu is thus owned by the filebrowser plugin and gets to make the decision about what items are in its own menu. Right now (without much thought) there are menu items for new notebook/file. As you have noticed, this leaves out all non-file activities such as terminals, consoles and .... wizards ;-)

To address this we plan on adding a much more powerful "launcher" that any plugin ca use to register its activities. Here is the issue that tracks that #848 

I should note that as we move to the launcher, the new notebook/file actions will likely be removed from the "file" menu.

Would you mind giving us feedback on that launcher issue? Can we close this one in favor of that more general discussion of how plugins can allow users to create new activities?

**Comment by svenefftinge** [comment] 2016-09-07 09:15
@ellisonbg Could you elaborate on what made the design so complicated? Or are there parts of the discussion even being online somewhere?

I am asking because I think plugins should really be able to contribute to common top level menu items like 'File', 'Edit', 'View' or 'About/Help'. Forcing a top level menu per plugin IMHO will result in bad UX.

This kind of problem has been nicely solved in other platforms (e.g. Eclipse, IntelliJ, VSCode). So maybe we can learn from those solutions.

**Comment by ellisonbg** [comment] 2016-09-08 20:06
@svenefftinge sure I can try to summarize some of the main points. For more reading, please see this issue (it is a huge one, looks towards the bottom):

https://github.com/jupyter/design/issues/20

### How are menus organized?

We surveyed the existing notebooks menu items to give us an inventory of all of the menu items we might need across our core plugins (notebook, terminal, editor). After a lot of work we realized that there were two main options for how to organize menus:

A. By plugin
B. By the type of action (File, Edit, View, Execute)

Here are mockups of two menus that follow each of those organizational approaches:

Option A (by plugin):

![92bf4680-2403-11e6-8299-1c6c4ff1b97e](https://cloud.githubusercontent.com/assets/27600/18364751/55f7bf94-75c4-11e6-92a4-775542abbd3a.png)

Option B (by type of action):

![565d14d8-2403-11e6-83b5-9af1114d84b2](https://cloud.githubusercontent.com/assets/27600/18364755/59584bae-75c4-11e6-97cf-7515416f897c.png)

What you see is that if we have a single "Edit" menu (option B), you end up with a ton of repeated menu items that do those actions on a particular plugin. Note that cut/copy/paste in the notebook is very different (at the cell level) than in a text editor so you need separate actions. This is very different from an environment that basically provides a text editor only. The only way of resolving that issue with option B is to make the menus modal - that is, rely on hidden state in the UI (such as which widget has focus) to selectively hide and show menu items. In general, highly modal UIs are a bad idea, and it is really difficult to get them right - especially in the browse where the focus semantics are very constrained.

Because of these issues, we decided to go with option A (menu per plugin).

**Comment by ellisonbg** [comment] 2016-09-08 20:11
Second issue:

### Ordering and sectioning

The other problem with option B is that you run into a lot of problems in providing an API that allows plugins to contirbute menu items and submenus and have them ordered in a sane and reproducible manner.

Some things we tried:

1. Topological sorting based on before/after semantics. Providing an API that allows plugins to specify those before/after dependencies for all menu items as horrifically complex - even we didn't want to use the system.
2. Providing basic numerical rank based sorting. In a system that has mostly built-in menu items and a few third party ones, that would probably work, but in JupyterLab, over time, we expect the number of third party menu items to far surpass the build-in ones. In that situation, the rank based ordering becomes impossible to reason about as you never know which plugins have claimed which part of the numerical ordering system. The other issue with this approach is that you have no promise that the numerical ordering will produce a usable interface once many plugins have dumped their menu items into the UI.

**Comment by ellisonbg** [comment] 2016-09-08 20:14
A few other comments on our current approach:

* Plugins own top level menus.
* The File menu is owned by the filebrowser plugin, so even though that one looks global/semantic, it is not.
* If plugins want to expose an API that allows other plugins to add menu items to its menu for a very specific purpose it can do so. Using this approach, we could allow the filebrowser plugin to have an API for adding additional "Create New" menu items for different types of documents.
* Because many types of activities (terminal, console, etc.) don't have a file representation, we wanted to provide a unified UX for creating new things. We are pursuing this so the filebrowser plugin can remain focused on core file logic only.

**Comment by ellisonbg** [comment] 2016-09-19 15:39
Thanks for the comment/question! We don't have any plans to change this now, so closing with as no action. I think some of the design issues you are bringing up will be resolve by other efforts.

**Closed by ellisonbg** 2016-09-19 15:39 UTC
Labels: type:Question
