### ISSUE TITLE
Make command palette a modal dialog?

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#507] opened 2016-07-22 02:16 UTC
From #318, for discussion.

**Comment by sccolbert** [comment] 2016-07-22 02:20
You mean instead of in the sidebar?

**Comment by jasongrout** [comment] 2016-07-22 03:12
Yes, I think that was what #318 was suggesting we discuss.

**Comment by ellisonbg** [comment] 2016-08-23 15:46
Closing as duplicate of #447

**Closed by ellisonbg** 2016-08-23 15:46 UTC
Labels: cat:Design and UX, status:Needs Discussion, type:Enhancement
