### ISSUE TITLE
Inconsistent navigation in Tour

### ISSUE THREAD

**Issue by cryptarch** [jupyter/jupyterlab#492] opened 2016-07-21 05:42 UTC
Hey there,

While taking the Tour, I noticed that sometimes it is possible to use arrow keys to scroll up and down, but after a while the arrow keys stop working until I click on one of the on-screen arrows. Ideally arrow keys should keep working all the time, but I propose that JL should at least behave consistently to avoid switching back and forwards between the two ways of navigating.

This inconsistent behaviour is especially easy to reproduce if you change tabs within JL while taking the tour. When you change tabs back to the tour, it is no longer possible to navigate with arrow keys. However, the inconsistent behaviour still often occurs even without changing tabs.

Let me know if anything is unclear or you need more information.

**Comment by blink1073** [comment] 2016-07-21 20:32
Thanks for the report, @cryptarch.  cc @eskirk, @rnetro.

**Comment by rnetro** [comment] 2016-07-21 21:01
Thanks! on it :)

**Comment by rnetro** [comment] 2016-07-21 21:10
So, after some investigating it's a widget focus issue. We can't automatically focus a tab's contents because it will mess with other widgets.
Clicking anywhere in the widget screen will re-focus the page and allow you to scroll again.

**Comment by rnetro** [comment] 2016-07-21 21:10
(recommending closing this issue)

**Comment by sccolbert** [comment] 2016-07-21 21:20
In the new phosphor monorepo, clicking on a tab will send an activation request to the relevant widget. This will give the widget the opportunity to refocus, which sounds like what is needed here.

I'd leave this open until we handle that.

**Comment by ellisonbg** [comment] 2016-08-25 17:31
@rnetro the mono repo has been merged, so we should be able to fix this (if it isn't already). Could you have a look?

**Comment by rnetro** [comment] 2016-08-25 22:27
@ellisonbg Can I do a share-my-screen with you tomorrow so we're on the same page with the problem?

**Comment by ellisonbg** [comment] 2016-08-31 18:38
In master right now, if you click on the tour to focus it, the keyboard shortcuts start to work as expected. Obviously, when other parts of the page are focused, they receive keyboard events and not the tour, but that is by design. We are working on the visual design of the dock panel to make it more clear which widget has focus and that should help some of this as well.

**Closed by ellisonbg** 2016-08-31 18:38 UTC
Labels: monorepo, type:Bug

**Comment by cryptarch** [comment] 2016-08-31 20:12
@ellisonbg Thanks!
