### ISSUE TITLE
Markup not being read correctly in Jupyter Lab

### ISSUE THREAD

**Issue by eskirk** [jupyter/jupyterlab#63] opened 2016-06-14 18:10 UTC
![screen shot 2016-06-14 at 11 08 22 am](https://cloud.githubusercontent.com/assets/7052378/16054057/4ffcb24e-3220-11e6-89dc-b67000fd665e.png)

The image on the left is the Jupyter notebook. In this image it is correctly interpreting markdown text and formatting, correctly showing a numbered list along with stylized functions.

On the right we have Jupyter lab. The numbered list is incomplete and the functions are not stylized. When I looked further into this problem, I found that the text simply stops displaying once it hits a less than ('<') character. The only reason this issue isn't occurring at the end of list item 1 is because I put a space around the less than character and it is now being interpreted as '&lt'. Not too sure why this is, just putting this issue out there.

**Comment by blink1073** [comment] 2016-06-14 18:43
Hi @eskirk, thanks for the report, do you mind pasting the contents of that cell here for testing?

**Comment by jasongrout** [comment] 2016-06-14 19:06
At first glance, it looks like the function that is supposed to strip out math before markdown processing isn't working, so none of the math is getting processed and the `<` in the math is being interpreted as the start of an html sequence in markdown.

**Comment by jasongrout** [comment] 2016-06-14 21:10
Looks like someone (probably me) commented out the mathjax in the html template, preventing us from rendering it.

**Comment by eskirk** [comment] 2016-06-14 21:57
Should it be working now? Because I just updated my build of the lab and it's still not quite working on my end.

**Comment by jasongrout** [comment] 2016-06-14 22:28
My PR hasn't been merged yet.

**Comment by blink1073** [comment] 2016-06-15 03:32
@eskirk, this should be good to go now that #66 is merged, can you confirm?

**Comment by eskirk** [comment] 2016-06-15 04:01
@blink1073 the functions are stylized now, but the greater than sign is still being interpreted as an end of line or something and all of the following text is cut off.

**Comment by jasongrout** [comment] 2016-06-15 04:07
Yep, I'm also seeing that `$x<y$` is not typesetting correctly. Reopening this issue...

**Comment by jasongrout** [comment] 2016-06-15 04:24
Okay, now the problem is that at https://github.com/jupyter/jupyterlab/blob/master/src/notebook/cells/widget.ts#L471, the sanitizer converts `<` to `&lt;`, and then later at https://github.com/jupyter/jupyterlab/blob/master/src/renderers/latex.ts#L194, the `&` is converted to `&amp;`. So things are double-escaped. I think the sanitizer is being run too early (it's run before the markdown is generated, for exampe).

**Closed** 2016-06-15 13:14 UTC
Labels: type:Bug, type:Feature Parity

**Comment by jasongrout** [comment] 2016-06-15 13:18
@eskirk - can you confirm that things are fixed now?

**Comment by eskirk** [comment] 2016-06-15 16:05
@jasongrout seems to be working on my end.

**Comment by jasongrout** [comment] 2016-06-15 16:53
Great! Thanks again for reporting this.
