### ISSUE TITLE
Error Install jupyterlab

### ISSUE THREAD

**Issue by jmarcellopereira** [jupyter/jupyterlab#788] opened 2016-08-27 14:59 UTC
jmarcellopereira@kubuntu:~/maxima-jupyter-master$ jupyter serverextension enable --py jupyterlab --sys-prefix
Enabling: jupyterlab
- Writing config: /usr/etc/jupyter
Traceback (most recent call last):
  File "/home/jmarcellopereira/.local/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/notebook/serverextensions.py", line 301, in start
    super(ServerExtensionApp, self).start()
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/notebook/serverextensions.py", line 218, in start
    self.toggle_server_extension_python(arg)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/notebook/serverextensions.py", line 210, in toggle_server_extension_python
    self.toggle_server_extension(module)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/notebook/serverextensions.py", line 193, in toggle_server_extension
    sys_prefix=self.sys_prefix, logger=self.log)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/notebook/serverextensions.py", line 81, in toggle_serverextension_python
    cm.update("jupyter_notebook_config", cfg)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/traitlets/config/manager.py", line 87, in update
    self.set(section_name, data)
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/traitlets/config/manager.py", line 71, in set
    self.ensure_config_dir_exists()
  File "/home/jmarcellopereira/.local/lib/python2.7/site-packages/traitlets/config/manager.py", line 46, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/etc'
jmarcellopereira@kubuntu:~/maxima-jupyter-master$ 

jmarcellopereira@kubuntu:~/maxima-jupyter-master$ sudo jupyter serverextension enable --py jupyterlab --sys-prefix
sudo: jupyter: comando não encontrado
jmarcellopereira@kubuntu:~/maxima-jupyter-master$ 

:(

**Comment by AbdealiJK** [comment] 2016-08-28 05:11
I faced a similar issue earlier. The issue is that the `--sys-prefix` tries to make it a global. But it won't work if you have not installed jupyter globally.
Doing a `pip install jupyter` in Ubuntu makes it install the jupyter in `~/.local/` folder rather than a system folder. And doing `sudo` doesn't work here because root doesn't have jupyter installed.

Hence, the fix  here is to not use --sys-prefix but use --user instead.
`jupyter serverextension enable --py jupyterlab --user`

**Comment by blink1073** [comment] 2016-08-29 12:14
Hi @jmarcellopereira, there is current discussion on how to improve this experience: https://github.com/jupyter/notebook/issues/1706

**Comment by ellisonbg** [comment] 2016-09-06 18:25
Closing as these commands are not part of this repo and we are aware of and tracking the problems on the jupyter/notebook repo. 

However, for now, the fix is to use `--user` rather than `--sys-prefix` when installing or activating jupyter nbextensions if you find you don't have permission to write to system direcoties.

**Closed by ellisonbg** 2016-09-06 18:25 UTC
Labels: cat:Build System

**Comment by SylvainCorlay** [comment] 2016-09-08 09:19
> However, for now, the fix is to use --user rather than --sys-prefix when installing or activating jupyter nbextensions if you find you don't have permission to write to system direcoties.

 - --sys-prefix should always require the same permissions as the pip installation of the package.
 - I experienced issues for `serverextensions` specifically with sys-prefix that don't appear enabled. Enabling as user or system-wide seems to work though.
