### ISSUE TITLE
Editor: Horizontal Scrollbar 1/2 hidden

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#815] opened 2016-08-31 02:18 UTC
When a line is sufficiently long to trigger the horizontal scrollbar to appear it is 1/2 hidden (on Mac OS 10.10.3, Chrome 53)

<img width="676" alt="screen shot 2016-08-30 at 19 15 40" src="https://cloud.githubusercontent.com/assets/335567/18113627/3b3dbe54-6ee6-11e6-8bc4-03da61995121.png">

**Comment by sccolbert** [comment] 2016-08-31 02:34
Do you think this is something we're doing, or a code mirror issue?

**Comment by Carreau** [comment] 2016-08-31 16:00
I think it is due to the 4 pitel top margin on the editor:

```
.jp-EditorWidget {
    border-top: 1px solid #E0E0E0;
    margin-top: 4px;  // this one
}
```

Removing it for fixes things though I doubt it's the right fix as it removes the 4 pixel border at top conveying it's a panel.
In general the `.jp-EditrWidget` seem to overflow by a few pixel at the bottom from it's containing `p-Widget p-Panel p-StackedPanel p-TabPanel-stackedPanel` you can see that when hovering the dom element in the inspector; attempt at a screenshot:

<img width="814" alt="screen shot 2016-08-31 at 08 58 04" src="https://cloud.githubusercontent.com/assets/335567/18136159/30cc2ca8-6f59-11e6-8c19-b1362e09ef62.png">

Does that make sens ?

**Comment by sccolbert** [comment] 2016-08-31 16:24
Yep. This is our CSS bug.

cc @afshin

**Comment by afshin** [comment] 2016-09-06 13:27
I can't reproduce this. Perhaps a different CSS fix has resolved this.

In the text editor I get line wrapping:

<img width="1056" alt="editor" src="https://cloud.githubusercontent.com/assets/159529/18275216/e80ee85e-743d-11e6-893a-6aae2b436652.png">

In the console, I can see the full scrollbar:

<img width="1056" alt="console" src="https://cloud.githubusercontent.com/assets/159529/18275258/f634f432-743d-11e6-8f46-bb06d793fac3.png">

And in the notebook, I can see the full scrollbar:

<img width="1052" alt="notebook" src="https://cloud.githubusercontent.com/assets/159529/18275269/02f7cca8-743e-11e6-8af9-0eff26fd0b8f.png">

@Carreau, could you please confirm if this is still happening for you?

**Comment by sccolbert** [comment] 2016-09-06 15:37
@afshin It looks liek the issue is with the horizontal scrollbar on the text editor being clipped. Not the code cells.

**Comment by sccolbert** [comment] 2016-09-06 15:38
also, I don't think line-wrapping on the text editor is a good default. But maybe i'm in the minority there.

**Comment by afshin** [comment] 2016-09-06 16:19
@sccolbert yeah, I just couldn't generate a horizontal scrollbar on the editor.

**Comment by jasongrout** [comment] 2016-09-06 16:47
> also, I don't think line-wrapping on the text editor is a good default. But maybe i'm in the minority there.

For me, it depends a lot on the filetype. I look forward to our settings system so we can have per-filetype wrapping.

**Comment by afshin** [comment] 2016-09-29 12:05
Closing because there hasn't been an update in a while; I couldn't reproduce it and it didn't arise again as an issue.

**Closed by afshin** 2016-09-29 12:05 UTC
Labels: cat:Design and UX, component:File Editor, status:Needs Info, type:Bug
