### ISSUE TITLE
Most Recent Build 

### ISSUE THREAD

**Issue by roshancvp** [jupyter/jupyterlab#216] opened 2016-07-01 18:34 UTC
When @charnpreetsingh185 and I updated and rebuilt jupyterlab nothing is visible on the screen although the project rebuilt without any errors.

![screen shot 2016-07-01 at 11 30 39 am](https://cloud.githubusercontent.com/assets/12474166/16530976/4752039e-3f7f-11e6-9761-e963d751ba1f.png)

**Comment by sccolbert** [comment] 2016-07-01 18:34
You see any errors in the dev tools console?

**Comment by charnpreetsingh185** [comment] 2016-07-01 18:36
![screen shot 2016-07-01 at 11 35 23 am](https://cloud.githubusercontent.com/assets/16314651/16531149/089773cc-3f80-11e6-8881-cdaf9d08bdf6.png)

**Comment by roshancvp** [comment] 2016-07-01 18:40
This is where the error points to:

![screen shot 2016-07-01 at 11 39 26 am](https://cloud.githubusercontent.com/assets/12474166/16531263/8b488bbc-3f80-11e6-8ecc-6d4b0e758aaf.png)

**Comment by sccolbert** [comment] 2016-07-01 18:42
That error is telling us what the problem is. A service is getting registered, but has already been provided by some other plugin. My guess is that someone copy-pasted extension boilerplate, and forgot to change the id.

**Comment by blink1073** [comment] 2016-07-01 18:43
This is fixed by #215.

**Comment by sccolbert** [comment] 2016-07-01 18:48
Wow. My guess was *completely* wrong.

**Comment by sccolbert** [comment] 2016-07-01 18:49
Though, this does introduce something which may be a common error, which we can catch in phosphide and provide a more accurate error message.

**Closed** 2016-07-02 01:21 UTC
