### ISSUE TITLE
One console sending keyboard events to another one instead of itself

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#229] opened 2016-07-05 19:34 UTC
This is really bizarre, no idea how to replicate it.  It happened after reporting #228: we went back to that console, and now in its input area, we can't execute code anymore. Typing works, but `Shift-Enter` doesn't do anything.

More strangely, we then opened a *new* console, and we noticed that the new console *is* getting the kbd events of the old one. Here's an illustration: we typed a `print` stmt into `Console-1`, then hit `Shift-Enter`, and then magically it was `Console-6` that executed it (where I had left a pre-typed `print` statement as well, but without cursor focus):

![image](https://cloud.githubusercontent.com/assets/57394/16597223/a684cf10-42ac-11e6-90b9-ce2896b5dcbf.png)

**Comment by afshin** [comment] 2016-07-06 19:38
I love the weird ones. I'll take a look.

**Comment by fperez** [comment] 2016-07-07 18:45
@ellisonbg had some thoughts on this one, he mentioned it might be an issue with the CSS selectors used for trapping the `Shift-Enter` (and similar) event getting confused/overwritten/something.  Because interestingly, all consoles still allowed for typing. It's just `Shift-Enter` that was a problem.

**Comment by afshin** [comment] 2016-07-07 18:46
@blink1073 and I talked about it and realized what the issue is. It's basically that the consoles weren't being tracked with the new `WidgetTracker` class.

**Comment by fperez** [comment] 2016-07-07 18:47
Great, glad to hear you have a handle on it, thanks!

**Comment by blink1073** [comment] 2016-07-07 21:55
Fixed by #248.

**Closed by blink1073** 2016-07-07 21:55 UTC
Labels: type:Bug
